services:
  db:
    image: mysql:8.0
    container_name: portfolio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio   # optional: bikin DB otomatis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # arahkan ke folder init

volumes:
  db_data:
